package es.example.lineafacturas.adapters.persistence.entities;

import jakarta.persistence.*;
import lombok.*;


import es.example.facturas.adapters.persistence.entities.FacturaEntity;




// Autogenerated LineaFactura persistence entity class.

@Entity
@Data
public class LineaFacturaEntity {

    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    private Long id;
    
    private String descripcion;
    
    private int cantidad;


    @ManyToOne
    @JoinColumn(name = "factura_id")
    private FacturaEntity factura;



}
