package <%= package %>;

import lombok.*;
<% if (needsListImport) { %> import java.util.List; <% } %>
<% if (dataBaseEngine === 'MongoDB') { %>
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.bson.types.ObjectId;
<% } else { %>
import jakarta.persistence.*;
<% for (importStatement of relationImports) { %>
import <%= importStatement %>;
<% } %>
<% } %>
// Autogenerated <%=model%> entity class.

@Data
<% if (dataBaseEngine === 'MongoDB') { %>@Document(collection = "<%= model.toLowerCase() %>")<% } else { %>@Entity
@Table(name = "<%=model.toLowerCase()%>")<% } %>
public class <%=model%>Entity {

    @Id<% if (DBtype==='Sql') { %>
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;<% } else { %> private ObjectId id;<% } %>
<% for (field of fields) { %>
    private <%= field.type %> <%= field.name %>;<% } %>
<% if (DBtype==='Sql') { %>
<% for (rel of relations) { 
    if (rel.type === "OneToMany") { %>
    
<% } else if (rel.type === "ManyToOne") { %>
    @ManyToOne
    @JoinColumn(name = "<%= rel.fieldName %>_id")
    private <%= rel.targetEntity %>Entity <%= rel.fieldName %>;
<% } else if (rel.type === "OneToOne") { %>
    @OneToOne
    @JoinColumn(name="<%= rel.targetEntity.toLowerCase() %>id")
    private <%= rel.targetEntity %>Entity <%= rel.fieldName %>;
<% } else if (rel.type === "ManyToMany") { 
    if (rel.owner) { %>
        @ManyToMany
        @JoinTable(
            name = "<%= [model.toLowerCase(), rel.targetEntity.toLowerCase()].sort().join('_') %>",
            joinColumns = @JoinColumn(name = "<%= model.toLowerCase() %>_id"),
            inverseJoinColumns = @JoinColumn(name = "<%= rel.targetEntity.toLowerCase() %>_id")
        )
        private List<<%= rel.targetEntity %>Entity> <%= rel.fieldName %>;
    <% } else { %>
        @ManyToMany(mappedBy = "<%= rel.mappedBy %>")
        private List<<%= rel.targetEntity %>Entity> <%= rel.fieldName %>;
    <% } %>
<% } } %>

<% } else { %>
<% for (rel of relations) { if (rel.type === "ManyToOne") { %>
    private ObjectId <%= rel.fieldName %>Id;<% } else if (rel.type === "OneToOne") { %>
    private ObjectId <%= rel.fieldName %>Id;<% } else if (rel.type === "ManyToMany") { %>
    private List<ObjectId> <%= rel.fieldName %>Ids;<% } } %>
<% } %>
}


