package <%= package %>;

import lombok.*;
<% if (needsListImport) { %> import java.util.List; <% } %>
<% if (databaseEngine === 'mongodb') { %>
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.bson.types.ObjectId;
<% } else { %>
import jakarta.persistence.*;
<% for (importStatement of relationImports) { %>
import <%= importStatement %>;
<% } %>
<% } %>
// Autogenerated <%=model%> entity class.

@Data
<% if (databaseEngine === 'mongodb') { %>@Document(collection = "<%= model.toLowerCase() %>")
<% } else { %>@Entity
<% } %>
public class <%=model%>Entity {

    @Id
    <% if (databaseEngine !== 'mongodb') { %>
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    <% } else { %>private ObjectId id; <% } %>


    <% for (field of fields) {%>
    private <%= field.type %> <%= field.name %>;
    <%} %>
    <% if (databaseEngine !== 'mongodb') { %>
    <% for (rel of relations) {%>
    <% if (rel.type === "OneToMany") { %>
    @OneToMany(mappedBy = "<%= rel.mappedBy %>")
    private List<<%= rel.targetEntity %>Entity> <%= rel.fieldName %>;
    <% } else if (rel.type === "ManyToMany") { %>
    @ManyToMany
    private List<<%= rel.targetEntity %>Entity> <%= rel.fieldName %>;
    <% } else if (rel.type === "ManyToOne") { %>
    @ManyToOne
    @JoinColumn(name = "<%= rel.fieldName %>_id")
    private <%= rel.targetEntity %>Entity <%= rel.fieldName %>;
    <% } else if (rel.type === "OneToOne") { %>
    @OneToOne
    private <%= rel.targetEntity %>Entity <%= rel.fieldName %>;
    <% } %>
    <%} %>
    <% } else { %>
    <% for (rel of relations) {%>
    <% if (rel.type === "ManyToOne") { %>
    private ObjectId <%= rel.fieldName %>;
    <% } else if (rel.type === "OneToOne") { %>
    private ObjectId <%= rel.fieldName %>;
    <% } else if (rel.type === "ManyToMany") { %>
    private List<ObjectId> <%= rel.fieldName %>;
    <% } %>
    <%} %>
    <% } %>
}
