package <%= groupID %>;

import <%= pathEntity %>.<%= entityName %>Entity;
<% if (databaseEngine === 'mongodb') { %>
import org.springframework.data.mongodb.repository.MongoRepository;
import org.bson.types.ObjectId;
<% } else { %>
import org.springframework.data.jpa.repository.JpaRepository;
<% } %>
import org.springframework.stereotype.Repository;

// Autogenerated <%= entityName %> Repository interface.

@Repository
public interface <%= entityName %>SpringRepository extends 
    <% if (databaseEngine === 'mongodb') { %>
        MongoRepository<<%= entityName %>Entity, ObjectId>
    <% } else { %>
        JpaRepository<<%= entityName %>Entity, Long>
    <% } %> {
}
