package <%= package %>;

import <%=pathModel%>.<%=model%>;

import java.util.List;

// Autogenerated <%= model %> UseCase interface class.

public interface <%= model %>UseCase {
    List<<%= model %>> getAll();

    <%= model %> save(<%= model %> <%= modelVarName %>);

    <%= model %> getById(String id);

    <%= model %> update(<%= model %> <%= modelVarName %>);

    Boolean delete(String id);
}