package <%= package %>;

import <%=pathModel%>.<%=model%>;
import <%=pathRepository%>.<%=model%>RepositoryPort;
import <%=pathUseCase%>.<%=model%>UseCase;
import <%=pathUseCaseAnnotation%>.UseCase;

import java.util.List;

// Autogenerated <%= model %> UseCase implementation class.

@UseCase
public class <%= model %>UseCaseImpl implements <%= model %>UseCase {
    private final <%= model %>RepositoryPort <%= modelVarName%>Repository;

    public <%= model %>UseCaseImpl(<%= model %>RepositoryPort <%= modelVarName%>Repository) {
        this.<%= modelVarName%>Repository = <%= modelVarName%>Repository;
    }

    public List<<%= model %>> getAll(){
        return <%= modelVarName%>Repository.findAll();
    }

    public <%= model %> save(<%= model %> <%= modelVarName%>){
        return <%= modelVarName%>Repository.save(<%= modelVarName%>);
    }

    public <%= model %> getById(String id){
        return <%= modelVarName%>Repository.findById(id);
    }

    public <%= model %> update(<%= model %> <%= modelVarName%>) {
        return <%= modelVarName %>Repository.update(<%= modelVarName %>);
    }

    public Boolean delete(String id){
        return <%= modelVarName%>Repository.deleteById(id);
    }
}