package <%= groupID %>;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

// Autogenerated <%=model%> domain entity class.

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class <%=model%> {

    private Long id;
    private String text;


}