package <%= package %>;

import lombok.*;
<% if (needsListImport) { %>
import java.util.List;
<% } %>

// Autogenerated <%=model%> class.

@Data
public class <%=model%> {

    private String id;

    <% for (field of fields) {%>
    private <%= field.type %> <%= field.name %>;
    <%} %>
    <% for (rel of relations) {%>
    <% if (rel.type === "ManyToOne" || rel.type === "OneToOne") { %>
    private String <%= rel.fieldName %>Id; 
    <% } else if (rel.type === "ManyToMany") { %>
    private List<String> <%= rel.fieldName %>Ids;
    <% } %>
    <%} %>
}