package <%= groupID %>;

import lombok.*;

// Autogenerated <%=model%> domain entity class.

@Data
public class <%=model%> {

    <% fields.forEach(field => { -%>
        private <%= field.type %> <%= field.name %>;
    <% }) -%>


}