package <%= package %>;

import <%=pathModel%>.<%=model%>;

import java.util.List;

// Autogenerated <%=model%> Repository interface class.

public interface <%=model%>RepositoryPort{

    <%=model%> save(<%=model%> <%=modelVarName%>);

    <%=model%> findById(String strId);

    List<<%=model%>> findAll();

    Boolean deleteById(String strId);

    <%=model%> update(<%=model%> <%=modelVarName%>);

}
