package <%= groupID %>;

import <%=pathModel%>.<%=model%>;

import java.util.List;
import java.util.Optional;

// Autogenerated <%=model%>RepositoryPort class.

public interface <%=model%>RepositoryPort{

    <%=model%> save(<%=model%> <%=entityVarName%>);
    <%=model%> findById(String id);
    List<<%=model%>> findAll();
    <%=model%> update(<%=model%> <%=entityVarName%>);
    boolean deleteById(String id);

}
