package es.example.facturas.ports.driven;

import es.example.facturas.models.Factura;

import java.util.List;
import java.util.Optional;

// Autogenerated Factura Repository class.

public interface FacturaRepository{

    Factura save(Factura factura);
    Factura findById(Long id);
    List<Factura> findAll();
    Factura update(Factura factura);
    boolean deleteById(Long id);

}
