package es.example.facturas.models;

import lombok.*;

// Autogenerated Factura domain entity class.

@RequiredArgsConstructor
@ToString
@Getter
@Setter
public class Factura {

            private Long id;
            private String numero;
    

}