package es.example.lineafacturas.ports.driven;

import es.example.lineafacturas.models.LineaFactura;

import java.util.List;
import java.util.Optional;

// Autogenerated LineaFactura Repository class.

public interface LineaFacturaRepository{

    LineaFactura save(LineaFactura lineaFactura);
    LineaFactura findById(Long id);
    List<LineaFactura> findAll();
    LineaFactura update(LineaFactura lineaFactura);
    boolean deleteById(Long id);

}
