package es.example.users.ports.driven;

import es.example.users.models.User;

import java.util.List;
import java.util.Optional;

// Autogenerated User Repository class.

public interface UserRepository{

    User save(User user);
    User findById(Long id);
    List<User> findAll();
    User update(User user);
    boolean deleteById(Long id);

}
