package es.example.facturas.adapters.persistence.entities;

import jakarta.persistence.*;
import lombok.*;


import es.example.lineafacturas.adapters.persistence.entities.LineaFacturaEntity;



import java.util.List;


// Autogenerated Factura persistence entity class.

@Entity
@Data
public class FacturaEntity {

    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    private Long id;
    
    private String numero;


    @OneToMany(mappedBy = "factura")
    private List<LineaFacturaEntity> lineas;



}
