package es.example.lineafacturas.models;

import lombok.*;

// Autogenerated LineaFactura domain entity class.

@RequiredArgsConstructor
@ToString
@Getter
@Setter
public class LineaFactura {

            private Long id;
            private String descripcion;
            private int cantidad;
    

}